### ISSUE TITLE
Menu look customization

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-context-menus#1]
Can we at least allow the menu bounding rectangle to be a rounded rectangle for flexible styling?

**Comment by metincansiper** [comment]
Users can set such 'css' properties using 'menuItemClasses' and 'contextMenuClasses' options and defining related 'css' classes in application level. I have added desired styling to 'demo-customized.html' in this way. I think that the same is true for #2 as well.
