### ISSUE TITLE
Submenus

### ISSUE THREAD

**Issue by ov7a** [iVis-at-Bilkent/cytoscape.js-context-menus#10]
Please, add the ability to create submenus. E.g. it can be implemented by adding `parent` option to menu item.

**Comment by dtsvetanov** [comment]
Hi @ugurdogrusoz, is there a chance of this being implemented soon?

**Comment by ugurdogrusoz** [comment]
@dtsvetanov Unfortunately not. We do not have the resources for it. Feel free do make a PR though.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Could you please review the demos and tidy them up? Combining them if possible and naming them properly...

**Comment by liuliuliuzy** [comment]
I want subMenus, too...
