### ISSUE TITLE
Cannot have multiple cytoscape instances side-by-side which each enable context menus.

### ISSUE THREAD

**Issue by finger563** [iVis-at-Bilkent/cytoscape.js-context-menus#11]
Only the most recently created cytoscape instance will have functional context menus. The other cytoscape instances will not respond to the right-click event (nothing will show up)

**Comment by metincansiper** [comment]
@finger563 It fixed this in master branch.  Would you verify that your problem is fixed?

**Comment by finger563** [comment]
Thanks, i'll check it shortly :)

**Comment by finger563** [comment]
It did fix it :) (though right clicking in one and then right clicking in the other did show both context menus at the same time, which might not be desired behavior)

**Comment by metincansiper** [comment]
To me it is the expected behaviour because these are two seperate instances.

**Comment by finger563** [comment]
Sounds good :)
