### ISSUE TITLE
Context menu 3.0.1 from npm is missing css files if build with webpack

### ISSUE THREAD

**Issue by pumpadump** [iVis-at-Bilkent/cytoscape.js-context-menus#14]
Hi,
I'm using the context menu in a project that is build with the react starter project (webpack).
It works locally, but when i run a production build (minified css + js) the css for the context menu is missing. If i revert back to 3.0.0 everything works fine.

best

Samy

**Comment by metincansiper** [comment]
Hi @pumpadump,
For the issue 'https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/issues/11' I needed to switch the selector of context menus from ```#cy-context-menus-cxt-menu``` to ```.cy-context-menus-cxt-menu``` (Now there should be one context menu for each cytoscape.js instance where this extension is initilized, so I needed to change it). As you can see changing it required a change in 'https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/blob/master/cytoscape-context-menus.css' as well. Do you use the updated css file? If not this may be the cause of the problem.

**Comment by kinimesi** [comment]
@pumpadump do you still have a problem with the minified css?

**Comment by kinimesi** [comment]
@pumpadump if you still have the same problem, please let us know.

**Comment by pumpadump** [comment]
Hi sry for the late reply, i can confirm that this issue is resolved by updating our css files
