### ISSUE TITLE
Context-menus out of the screen #1920

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-context-menus#17]
Report by @qtttttttttting

**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :  v3.1.2
- Browser/Node.js & version : chrome 59.0.3071.115

**Current (buggy) behaviour**

I use the context-menus of UI extension  , but when the node is on the right or bottom of the screen ,the context-menus will beyond the screen .And I see the source code ,it does not consider this situation.

207          var containerPos = $(cy.container()).offset();
208          var renderedPos = event.renderedPosition || event.cyRenderedPosition;
209
210          var left = containerPos.left + renderedPos.x;
211          var top = containerPos.top + renderedPos.y;
212
213          $cxtMenu.css('left', left);
214          $cxtMenu.css('top', top);

**Desired behaviour**

**Minimum steps to reproduce**

**Comment by kinimesi** [comment]
Please see https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/pull/19#issuecomment-342466661

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  you can test it in the simple demo the unstable branch.

**Comment by ugurdogrusoz** [comment]
thanks @nasimsaleh seems to work well
