### ISSUE TITLE
How to import to Ember?

### ISSUE THREAD

**Issue by BMahabir** [iVis-at-Bilkent/cytoscape.js-context-menus#22]
Can anyone tell me how to import this extension into my Ember project?  It's just not clear to me from the instructions given.  I have already installed it locally using npm install.  Thank you!

**Comment by ugurdogrusoz** [comment]
@BMahabir as can be seen from the name and description, this is a Cytoscape.js extension. Refer to [Cytoscape.js web page](http://js.cytoscape.org/#extensions) for help.
