### ISSUE TITLE
Context menu appears way off the screen, have to scroll to see it

### ISSUE THREAD

**Issue by BMahabir** [iVis-at-Bilkent/cytoscape.js-context-menus#23]
I simply cut-&-paste the example from the basic demo into my prototyping project, and this is the result.  First SS is right-clicking on whitespace, second SS is from right-clicking on a node.  Also the X appears at the very top-left of the screen (not shown).

![image](https://user-images.githubusercontent.com/1659720/34312985-f83d64be-e735-11e7-8786-ef64429ad3bb.png)
![image](https://user-images.githubusercontent.com/1659720/34312995-0a01b862-e736-11e7-867d-4acb18471b80.png)

**Comment by kinimesi** [comment]
@BMahabir It looks like you did not include CSS file. Make sure that you include [cytoscape-context-menus.css](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/blob/master/cytoscape-context-menus.css) file.
