### ISSUE TITLE
How use this extension with a left-click?

### ISSUE THREAD

**Issue by BMahabir** [iVis-at-Bilkent/cytoscape.js-context-menus#24]
I have fully fleshed out and implemented this extension in my project, and now management wants to be able to access context menus with a left-click instead of a right-click.  I don't want to scrap this and start over with a different extension/library/etc... is there any way to do this with this extension?  (or something equally simple).

Thanks for your time!

**Comment by kinimesi** [comment]
@BMahabir currently there is no option for changing the events which show and hide context menu (it is shown on right-click and hidden on left-click).

Please feel free to make a PR for displaying the context menu with left-click as an option.

**Comment by hasanbalci** [comment]
This can be achieved from now on with [v3.1.0](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/releases/tag/v3.1.0) by using `evtType` option.
