### ISSUE TITLE
Node-specific data as text in context menu?

### ISSUE THREAD

**Issue by hippofant** [iVis-at-Bilkent/cytoscape.js-context-menus#25]
Hi,

Is there a way to use the context menu itself to show information attached to the node in CytoJS? With the onClickFunction, I can target the node using event.target and access its attributes, but I'd like to do something similar with the static text. So something like:

```
                id: 'link',
                content: 'Visit ' + node.data('url'),
                tooltipText: 'Opens in a new window!',
                selector: 'node',
                onClickFunction: function (event) {
                  window.open(event.target.data('url'));
                },
                hasTrailingDivider: true
```
So the user could be informed where the link is going, depending on the node they're clicking.

**Comment by kinimesi** [comment]
@hippofant Currently the content field only accepts text. But you can achieve the desired functionality by combining Cytoscape.js event and jQuery, see [this example](http://jsbin.com/tehumurudu/)
