### ISSUE TITLE
Remove dependence of jQuery

### ISSUE THREAD

**Issue by calebeaires** [iVis-at-Bilkent/cytoscape.js-context-menus#27]
Our tean intend to use it on a angular 6 project. How to use this extension without jQuery dependece?

**Comment by kinimesi** [comment]
@calebeaires currently there is no way of using this extension without jQuery, it is heavily dependent on jQuery.

At the moment, we do not have enough resources to allocate to this issue. If you would like to remove jQuery dependency, feel free to make a pull request.

Thanks.

**Comment by alejoar** [comment]
I wish this too

**Comment by Raven0us** [comment]
Bump @ this. Are there any bugs that need to be addressed in order to make `unstable` -> `master` merge possible?

**Comment by ugurdogrusoz** [comment]
@Raven0us Not anything we know of. Feel free to test and let us know. We normally do a thorough test once a year or so and then do a merge and publish a module.
