### ISSUE TITLE
How to use this with ES6 module syntax

### ISSUE THREAD

**Issue by rkaliyug** [iVis-at-Bilkent/cytoscape.js-context-menus#29]
Hi,

I am trying to use this plug-in with ReactJs using import module concept. I have tried as below but not working. Would you please throw some light on this about how to make it work with Es6 module system

import jquery from "jquery";
import contextMenus from "cytoscape-context-menus";
 class myclass extends React.Component {
   constructor(){
     // Plug-in to support context-menu
    contextMenus( cytoscape, jquery ); // register extension
}
componentDidMount() {
    this.cy = ....// creating cytosccape instance or core
    this.cy.contextMenus( this.options);
  }
}

**Comment by rkaliyug** [comment]
Its working but getting displayed in somewhere cornor of the UI..Would you help me to display it on the mouse click location?

**Comment by kinimesi** [comment]
ES6 syntax:
```js
import $ from 'jquery';                                                         
import contextMenus from 'cytoscape-context-menus';                             

// register extension
cytoscape.use(contextMenus, $);                                                                                                                                                                       

// import CSS as well
import 'cytoscape-context-menus/cytoscape-context-menus.css'; 
```
I believe you don't import the CSS. Make sure that you import the CSS as well.

**Comment by rkaliyug** [comment]
Thanks [kinimesi](/kinimesi). It works now.

Any reason why i have to import it separately?

**Comment by kinimesi** [comment]
Currently, our extension does not have support for submenus https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/issues/10
