### ISSUE TITLE
Different set of menuitems per node

### ISSUE THREAD

**Issue by Marooned-MB** [iVis-at-Bilkent/cytoscape.js-context-menus#31]
Hi
Is there a way to have different menu items for particular nodes?
In my graphs nodes have different states (and classes) like "success", "running" etc - I would like to display different set of menu items for particular class. How can I achieve that?

I can see `selector` field but in some example I saw syntax like `node[?foo]` and `node[!foo]` but couldn't find that in the documentation.

Thanks

**Comment by hasanbalci** [comment]
It is not written in the documentation explicitly, but you can use selector field with Cytoscape.js [selectors](http://js.cytoscape.org/#selectors). 

Here are some examples from another application: 
https://github.com/iVis-at-Bilkent/newt/blob/2c7697db7e613f43dcb5de94003a1573c35b3760/app/js/app-cy.js#L124 and https://github.com/iVis-at-Bilkent/newt/blob/2c7697db7e613f43dcb5de94003a1573c35b3760/app/js/app-cy.js#L137

**Comment by Marooned-MB** [comment]
Oh great, that make sense. Thanks!

**Comment by Raven0us** [comment]
> It is not written in the documentation explicitly, but you can use selector field with Cytoscape.js [selectors](http://js.cytoscape.org/#selectors).
> 
> Here are some examples from another application:
> https://github.com/iVis-at-Bilkent/newt/blob/2c7697db7e613f43dcb5de94003a1573c35b3760/app/js/app-cy.js#L124 and https://github.com/iVis-at-Bilkent/newt/blob/2c7697db7e613f43dcb5de94003a1573c35b3760/app/js/app-cy.js#L137

Should be written in the docs, it's a valuable piece of information. It's the only way you can conditionally display/hide menu items, the `show` property can't be used with a callback.

**Comment by ugurdogrusoz** [comment]
@Raven0us makes sense. @hasanbalci let's please make sure it's mentioned in the README.
