### ISSUE TITLE
Demo is confusing

### ISSUE THREAD

**Issue by alihanokka** [iVis-at-Bilkent/cytoscape.js-context-menus#32]
- The selected layout in the demos('simple' and 'customized') puts multiple edges on top of each other. So, it seems as if the menu items, hide and remove, are not working properly.

![Peek 2019-09-03 16-58](https://user-images.githubusercontent.com/15351692/64180984-5cca5880-ce6e-11e9-8ad7-75c6294b6ab2.gif)

- A minor detail, but it is stated that the third demo is 'with different menu items'. But the differences between the first demo are having one extra menu item and removed symbols in front of the menu items. Maybe we can change the menu items a bit more or just remove the demo?

**Comment by ugurdogrusoz** [comment]
Let's also make the demos consistent (border vs no border and layout)

**Comment by nasimsaleh** [comment]
The last demo has an extra menu item to undo the last remove of a node or an edge. It only appears if a node or an edge is deleted. the 'customized' demo is different now to clearly show different styling.

**Comment by ugurdogrusoz** [comment]
@alihanokka Please check and close if you think it's OK as well.
