### ISSUE TITLE
Display context menu on touch screen

### ISSUE THREAD

**Issue by invaders-xx** [iVis-at-Bilkent/cytoscape.js-context-menus#35]
I am not able to display the context menu on a touch screen : I tried with two fingers with no success.
Is there a way to bind the display of the menu on an event tap ou touch ?

Many thanks in advance,

David

**Comment by hasanbalci** [comment]
Two-finger tap is already bound to display menu. It works both in my laptop's and in my smartphone's touch screen. However, it is a little bit harder in the smartphone.

**Comment by Hoogkamer** [comment]
I also experience problems with the two-finger tap.
I created a PR to give the option to use taphold, which works better on touch screens in my experience.

Regards,
Michael

**Comment by hasanbalci** [comment]
Taphold option is added (especially for touchscreens) thanks to @Hoogkamer in the unstable branch. It will be available with the next release.
