### ISSUE TITLE
Problem with changing options

### ISSUE THREAD

**Issue by Hoogkamer** [iVis-at-Bilkent/cytoscape.js-context-menus#37]
Hi,
I want to be able to switch between a desktop-friendly and a mobile-friendly menu.

But when I recall cy.contextMenus(options) with new options it does not seem to work correctly anymore:
- The menu pops up at a strange position
- Selectors don't work anymore.

Example, when I add this to demo.html after line 190
```
cy.contextMenus({
          menuItems: [
            {
              id: "removeNew",
              content: "remove NEW",
              tooltipText: "remove",
              image: { src: "remove.svg", width: 12, height: 12, x: 6, y: 4 },
              selector: "node, edge",
              onClickFunction: function(event) {
                var target = event.target || event.cyTarget;
                target.remove();
              },
              hasTrailingDivider: true
            },
            {
              id: "select-all-edges",
              content: "select all edges NEW",
              tooltipText: "select all edges",
              selector: "edge",
              onClickFunction: function(event) {
                selectAllOfTheSameType(event.target || event.cyTarget);
              }
            }
          ]
        });

```
I get this when I click on Kramer (or any other element)

![image](https://user-images.githubusercontent.com/17671871/71382486-6ff96380-25d8-11ea-8a4e-d41f48ed3dc6.png)

**Comment by hasanbalci** [comment]
@Hoogkamer I can't reproduce this issue. When I tried your example it works correctly. You can see it [here](https://jsbin.com/sojixeqepi/edit?html,css,js,output). Can you please provide a reproducible test case including OS and browser version?

**Comment by Hoogkamer** [comment]
You are right. I tested this by mistake with my local changed version in stead of the original.
I tried to implement the option for taphold, but did it wrong. 

Now it works, I will create a new PR for the proper taphold option.

Thanks for looking into this.
