### ISSUE TITLE
Context-menu isn't hidden on zoom and scroll

### ISSUE THREAD

**Issue by vitaly87** [iVis-at-Bilkent/cytoscape.js-context-menus#39]
Hi,
I am using context menu the issue that on scroll and zoom the menu isnt hide,
Do have any option to pass for this? also same for navigation from page to page its still present.

**Comment by ugurdogrusoz** [comment]
@vitaly87 If I understand correctly, you would like to close any open context menu on zoom or scroll. This extension does not support such behavior. Feel free to contribute by implementing it with a pull request.
