### ISSUE TITLE
API collisions etc

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-context-menus#4]
This extension writes many things to the global `Core` prototype.  That means you can have collisions with other extensions.  An extension is supposed to set only one field in the prototype of the core and/or collections -- the same as the extension name.

It would be better to have something like this:

```js
let menu = cy.contextMenu({ /* options... */ }); 
// or
let menu = cy.$('#some-node').contextMenu({ /* options... */ });

menu.enable();
menu.disable();
menu.add( someItem );
menu.remove( someItem );
menu.destroy();

// etc...
```

**Comment by metincansiper** [comment]
You are right I will fix this.

**Comment by metincansiper** [comment]
Now, the extension sets just one field (.contextMenus) in the core.

**Comment by maxkfranz** [comment]
Great!  Thanks
