### ISSUE TITLE
Is there any way to use contextMenus extension in Angular 9 application ?

### ISSUE THREAD

**Issue by ErnestManukyan** [iVis-at-Bilkent/cytoscape.js-context-menus#43]
compilation error `Property 'contextMenus' does not exist on type 'Core'.`

**Comment by canbax** [comment]
1. put `"node_modules/cytoscape-context-menus/cytoscape-context-menus.css"` inside the array `"styles"` inside the file "angular.json".

2. import the library and other necessary libraries inside a ts file like 

```
import cytoscape from 'cytoscape';
import * as contextMenus from 'cytoscape-context-menus';
import * as $ from 'jquery';
```

And then register the extension like `cytoscape.use(contextMenus, $);`. Then you can use it as described in the API of the extension.

**Comment by ErnestManukyan** [comment]
cytoscape.use() method has only one input parameter

**Comment by ErnestManukyan** [comment]
/**
     * Register imported extension into cytoscape
     * @param module Entry point for the extension, got by module = require('cy-ext')
     * or by import module from 'cy-ext'
     * http://js.cytoscape.org/#extensions
     */
    function use(module: Ext): void;

**Comment by canbax** [comment]
my dependencies are. It works fine for me.
```
    "cytoscape": "^3.14.2",
    "cytoscape-context-menus": "^3.1.0",
    "jquery": "^3.5.1",
```
did you try running?

**Comment by ErnestManukyan** [comment]
It's still not working.
First of all, I have a problem when trying to register the extension.

![image](https://user-images.githubusercontent.com/37364603/83354762-da72b480-a36b-11ea-87d1-038ea12472a2.png)

**Comment by ErnestManukyan** [comment]
I did update and the packages versions are the same as You have.

**Comment by ErnestManukyan** [comment]
Can you please share your use method's signature ?

**Comment by canbax** [comment]
I think you are importing types for cytoscape. I recommend you to not do that.

cytoscape.js and probably all of its extensions do **not** support typescript natively. There might be some wrappers around them to use typescript. 

You should import cytoscape and extensions as JAVASCRIPT modules. So there won't be any type information. With js the editor won't  show you such errors.

**Comment by ErnestManukyan** [comment]
@canbax helped me to change my code.
So, the problem was about importing types like typescript. We imported cytoscape and extensions as JAVASCRIPT modules and now everything works fine.
Dear @canbax thank you very much !!!
