### ISSUE TITLE
contextMenuClasses are not applied correctly

### ISSUE THREAD

**Issue by cosmorunner** [iVis-at-Bilkent/cytoscape.js-context-menus#44]
Hi there, 

when I use the following option:
`
contextMenuClasses: [
        'border',
        'm-0',
        'border-primary'
    ]
`

The classes are applied as shown here:
`<div class="border cy-context-menus-cxt-menu" m-0="" border-primary="" style="inset: auto 615px 432px auto;">...</div>`

It seems that only the first class is applied.
Or am I missing something?

Cheers!

**Comment by hasanbalci** [comment]
@cosmorunner It seems that you're right. I fixed the issue in the "unstable" branch. Can you please test and verify? If it's ok, the fix will be available with the next release.

**Comment by canbax** [comment]
I see the same issue. I can confirm that it is fixed. Thank you
