### ISSUE TITLE
cytoscape not defined in require

### ISSUE THREAD

**Issue by blacksmithblack** [iVis-at-Bilkent/cytoscape.js-context-menus#5]
Hi ...

I'm initialising the menu as suggested below

```
var cytoscape = require('cytoscape');
var contextmenus = require('cytoscape-context-menus');
contextmenus(cytoscape); // register extension
```

However I get the following error when I 'require' the context-menu.

> cytoscape-context-menus.js:420Uncaught ReferenceError: cytoscape is not defined
2318 @ cytoscape-context-menus.js:420
__webpack_require__ @ bootstrap 414671b…:50
2383 @ app.js:11__webpack_require__ @ bootstrap 414671b…:50
0 @ analysisCentre.entry.js:29
__webpack_require__ @ bootstrap 414671b…:50
webpackJsonpCallback @ bootstrap 414671b…:21
(anonymous function) @ analysisCentre.bundle.js?v=8467:1

Am I missing something?

**Comment by blacksmithblack** [comment]
Don't seem to be able to get the demo working either .... 

fiddle is here [https://jsfiddle.net/blacksmithsblack/wzoyzo4c/2/](url)

**Comment by metincansiper** [comment]
@blacksmithblack I made some fix on this issue. Is version 2.0.1 working for you in the following way?

var cytoscape = require('cytoscape');
    var jquery = require('jquery');
    var contextMenus = require('cytoscape-context-menus');
 
    contextMenus( cytoscape, jquery ); // register extension

**Comment by blacksmithblack** [comment]
Looks like I get this now ...

> cytoscape-context-menus.js:207Uncaught (in promise) TypeError: $ is not a function
    at createAndAppendCxtMenuComponent 

Apologies ... Demo is working ... my mouse isn't :(

**Comment by blacksmithblack** [comment]
Further .... 

>cytoscape-context-menus.js:207Uncaught (in promise) TypeError: $ is not a function(…)
createAndAppendCxtMenuComponent @ cytoscape-context-menus.js:207
(anonymous function) @ cytoscape-context-menus.js:395
(anonymous function) @ app.js:840
F @ $.export.js:30
initGraph @ app.js:787
(anonymous function) @ app.js:974
invoke @ angular.js:4478
extend.instance @ angular.js:9136
nodeLinkFn @ angular.js:8248
compositeLinkFn @ angular.js:7680
publicLinkFn @ angular.js:7555
link @ angular-route.js:985
invokeLinkFn @ angular.js:8789
nodeLinkFn @ angular.js:8289
compositeLinkFn @ angular.js:7680
publicLinkFn @ angular.js:7555
boundTranscludeFn @ angular.js:7699
controllersBoundTransclude @ angular.js:8316
update @ angular-route.js:935
$broadcast @ angular.js:16311
(anonymous function) @ angular-route.js:619
processQueue @ angular.js:14745
(anonymous function) @ angular.js:14761
$eval @ angular.js:15989
$digest @ angular.js:15800
$apply @ angular.js:16097done @ angular.js:10546
completeRequest @ angular.js:10744
requestLoaded @ angular.js:10685

**Comment by blacksmithblack** [comment]
Fantastic ... yes that works.

Thank you !

**Comment by metincansiper** [comment]
I think that it was an important bug thank you for letting me know it.
