### ISSUE TITLE
Menu options not correctly updated in unstable demos

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-context-menus#52]
In both of the demos in [unstable](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/tree/unstable), when select all nodes/edges options are used and then elements are manually unselected -via click on anywhere for example-, the option that appears on the context menu is still "unselect", even though elements are unselected already. Seems to be an oversight.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please check
