### ISSUE TITLE
manual trigger for showing/closing cxtMenu?

### ISSUE THREAD

**Issue by alhuber1502** [iVis-at-Bilkent/cytoscape.js-context-menus#54]
I'm trying to use _cytoscape.js-context-menus_ with the _edgehandles_ extensions and use the events defined in the latter to trigger UI options.

Is it possible to simply hide/show _cytoscape.js-context-menus_, like 
```
contextMenu = cy.contextMenus( options );
...
contextMenu.show(); or
contextMenu.hide();
```
and still get the selector-based options defined in the contextMenu options?

Thanks!

**Comment by mltn123** [comment]
DId you ever find a solution for that particular issue?

**Comment by alhuber1502** [comment]
Sadly no and  I didn't use the extension in the end.
