### ISSUE TITLE
Force remove trailing divider from last menu item

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-context-menus#56]
This problem should be handled at rendering level since menu items can be dynamically hidden/shown.

**Comment by msalihaltun** [comment]
I have now realized there is no easy way to implement this without major changes. May leave it up until later and come back to it.

**Comment by msalihaltun** [comment]
@hasanbalci can you confirm that it works?

**Comment by hasanbalci** [comment]
@msalihaltun Thanks, it works!
