### ISSUE TITLE
do not use standart button title attribute (to avoid standart browser tooltips)

### ISSUE THREAD

**Issue by grigorijski** [iVis-at-Bilkent/cytoscape.js-context-menus#8]
I propose to use custom attribute to display menu item title. If using standart "title" attribute tooltip is shown in addition to menu item (with same text) if I stay on item for a while

Proposed changes :

Library
```
220c220
<       var itemStr = '<button id="' + item.id + '" data-title="' + item.title + '" class="' + classStr + '"';
---
>       var itemStr = '<button id="' + item.id + '" title="' + item.title + '" class="' + classStr + '"';

```
CSS:
```
42,43c42,43
< .cy-context-menus-cxt-menuitem[data-title]:before {
<     content:attr(data-title);
---
> .cy-context-menus-cxt-menuitem[title]:before {
>     content:attr(title);
46c46
< .cy-context-menus-cxt-menuitem:not([data-title]):before {
---
> .cy-context-menus-cxt-menuitem:not([title]):before {

```

**Comment by metincansiper** [comment]
@grigorijski thanks for your suggestion I considered it. I renamed "title" option as "content" and added a "tooltipText" option which determines the tooltip text for a menu item. If you do not set this option for a menu item then that menu item will not have a tooltip. After making these changes I published v3.0.0. You can see  the discussion at #2. I am closing the issue if you need you can re-open.
