### ISSUE TITLE
No visible menu when used in Node.js

### ISSUE THREAD

**Issue by geirmeyer** [iVis-at-Bilkent/cytoscape.js-context-menus#9]
The menu is not shown when setting it up in a Node.js application.

By adding console.log messages into cytoscape-context-menus.js shows that the menu-system is used, for instance is function adjustCxtMenu() called from a right-click.

Page https://github.com/iVis-at-Bilkent/ lists cytoscape.js-context-menus as html and not javascript.
Is it not possible to use it within a Node.js application?

The menu has been set up as shown in attached node-js-test.txt file.

[node-js-test.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/files/732587/node-js-test.txt)

**Comment by metincansiper** [comment]
@geirmeyer we use this extension with commonjs. Please see 'https://github.com/iVis-at-Bilkent/sbgnviz.js-sample-app/'. Extension is registered here (https://github.com/iVis-at-Bilkent/sbgnviz.js-sample-app/blob/master/app/main.js#L30) and it is initilized here (https://github.com/iVis-at-Bilkent/sbgnviz.js-sample-app/blob/master/app/main.js#L30). Application is deployed to 'http://www.cs.bilkent.edu.tr/~ivis/SBGNViz_sample_app/' and menu is visible there.

**Comment by geirmeyer** [comment]
Thanks, yes it is working :) (my fault, the css file had been commented out....)
